apiVersion: v1
kind: Service
metadata:
  name: ps-1
spec:
  selector:
    name: ps-1
  ports:
    - port: 8491
      targetPort: 8491
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ps
  labels:
    name: ps-1
spec:
  containers:
  - name: test-ps
    image: yujmo/tensorflow
    command: ["/usr/bin/python","/notebooks/9_3_Distributed.py","--job_name=ps","--task_index=0"]
    imagePullPolicy: Never
  nodeSelector:
    accelerator: nvidia-tesla-p100
  restartPolicy: Never
