apiVersion: v1
kind: Service
metadata:
  name: worker-2
spec:
  selector:
    work: worker2
  ports:
    - port: 8493
      targetPort: 8493
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker2
  labels:
    work: worker2
spec:
  containers:
  - name: test-worker2
    image: yujmo/tensorflow:latest
    command: ["/usr/bin/python","/notebooks/9_3_Distributed.py","--job_name=worker","--task_index=1"]
    imagePullPolicy: Never
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia-tesla-p100
  restartPolicy: Never
