apiVersion: v1
kind: Service
metadata:
  name: worker-1
spec:
  selector:
    work: worker1
  ports:
    - port: 8492
      targetPort: 8492
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker1
  labels:
    work: worker1
spec:
  containers:
  - name: test-worker1
    image: yujmo/tensorflow
    command: ["/usr/bin/python","/notebooks/9_3_Distributed.py","--job_name=worker","--task_index=0"]
    imagePullPolicy: Never
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia-tesla-p100
  restartPolicy: Never
